---
title: "Visual Class 599B Class 3"
output: html_notebook
---

```{r}
link="https://raw.githubusercontent.com/jwhite00/VisualAnalytics_2_tabularData/master/Education%2070s%20to%2016.csv"
mydata=read.csv(link)
names(mydata)
```

```{r}
str(mydata,width = 150,strict.width='cut')
```


```{r}
library(ggplot2)
library(scales)

titleText='Bachelors degree or higher 2012-2016 per region'
sourceText = 'Source: US Department of State'
base= ggplot(data = mydata, 
             aes(x = Region,
                 y = Bachelor.s.degree.or.higher.2012.2016,
                 fill = Region))
plot = base + 
       geom_bar(stat = 'identity') +
       labs(
         title=titleText
         , x = 'Region'
         , y = '# of people who gets Bachelors degree or higher'
         , caption = sourceText
         ) +
       theme(
         panel.background = element_rect(fill = "white", colour = "grey50")
         , plot.title = element_text(hjust = 0.5, size=15)
         , axis.title = element_text(colour="black", size=11)
         , axis.text = element_text(colour="black", size=9)
         , axis.text.x = element_text(hjust=1)) +
       scale_y_continuous(
         breaks=c(0, 1000000, 2000000, 3000000, 4000000, 5000000)
         , limits = c(0, 5000000)
         , labels = comma)
plot
```

